version: "3"
services:

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring_network
    volumes:
      - grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb_container
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - monitoring_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
    env_file:
      - 'env.influxdb'

networks:
  monitoring_network:

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
